In [1]:
import pandas as pd

In [2]:
ufo = pd.read_csv('http://bit.ly/uforeports')
ufo

,City,Colors Reported,Shape Reported,State,Time
0,Ithaca,NaN,TRIANGLE,NY,6/1/1930 22:00
1,Willingboro,NaN,OTHER,NJ,6/30/1930 20:00
2,Holyoke,NaN,OVAL,CO,2/15/1931 14:00
3,Abilene,NaN,DISK,KS,6/1/1931 13:00
4,New York Worlds Fair,NaN,LIGHT,NY,4/18/1933 19:00
5,Valley City,NaN,DISK,ND,9/15/1934 15:30
6,Crater Lake,NaN,CIRCLE,CA,6/15/1935 0:00
7,Alma,NaN,DISK,MI,7/15/1936 0:00
8,Eklutna,NaN,CIGAR,AK,10/15/1936 17:00
9,Hubbard,NaN,CYLINDER,OR,6/15/1937 0:00
10,Fontana,NaN,LIGHT,CA,8/15/1937 21:00
11,Waterloo,NaN,FIREBALL,AL,6/1/1939 20:00
12,Belton,RED,SPHERE,SC,6/30/1939 20:00
13,Keokuk,NaN,OVAL,IA,7/7/1939 2:00
14,Ludington,NaN,DISK,MI,6/1/1941 13:00
15,Forest Home,NaN,CIRCLE,CA,7/2/1941 11:30
16,Los Angeles,NaN,NaN,CA,2/25/1942 0:00
17,Hapeville,NaN,NaN,GA,6/1/1942 22:30
18,Oneida,NaN,RECTANGLE,TN,7/15/1942 1:00
19,Bering Sea,RED,OTHER,AK,4/30/1943 23:00
20,Nebraska,NaN,DISK,NE,6/1/1943 15:00
21,NaN,NaN,NaN,LA,8/15/1943 0:00
22,NaN,NaN,LIGHT,LA,8/15/1943 0:00
23,Owensboro,NaN,RECTANGLE,KY,10/15/1943 11:00
24,Wilderness,NaN,DISK,WV,1/1/1944 10:00
25,San Diego,NaN,CIGAR,CA,1/1/1944 12:00
26,Wilderness,NaN,DISK,WV,1/1/1944 12:00
27,Clovis,NaN,DISK,NM,4/2/1944 11:00
28,Los Alamos,NaN,DISK,NM,6/1/1944 12:00
29,Ft. Duschene,NaN,DISK,UT,6/30/1944 10:00
...,...,...,...,...,...
18211,Holyoke,NaN,DIAMOND,MA,12/28/2000 18:00
18212,Carson,NaN,DISK,CA,12/28/2000 18:20
18213,Pasadena,GREEN,FIREBALL,CA,12/28/2000 19:10
18214,Austin,NaN,FORMATION,TX,12/29/2000 0:00
18215,El Campo,NaN,OTHER,TX,12/29/2000 9:00
18216,Garden Grove,ORANGE,LIGHT,CA,12/29/2000 16:10
18217,Berthoud Pass,NaN,TRIANGLE,CO,12/29/2000 19:30
18218,Sisterdale,NaN,DIAMOND,TX,12/29/2000 20:00
18219,Garden Grove,NaN,CHEVRON,CA,12/29/2000 20:30
18220,Shasta Lake,BLUE,DISK,CA,12/29/2000 20:30
18221,Franklin,NaN,DISK,NH,12/29/2000 20:50
18222,Albrightsville,NaN,OTHER,PA,12/29/2000 21:00
18223,Greenville,NaN,NaN,SC,12/29/2000 22:00
18224,Eufaula,NaN,DISK,OK,12/29/2000 23:30
18225,Simi Valley,NaN,FORMATION,CA,12/30/2000 10:00
18226,San Francisco,NaN,FORMATION,CA,12/30/2000 22:00
18227,San Francisco,NaN,TRIANGLE,CA,12/30/2000 22:00
18228,Kingsville,NaN,LIGHT,TX,12/31/2000 4:00
18229,Chicago,NaN,DISK,IL,12/31/2000 11:45
18230,Pismo Beach,NaN,OVAL,CA,12/31/2000 20:00
18231,Pismo Beach,NaN,OVAL,CA,12/31/2000 20:00
18232,Lodi,NaN,NaN,WI,12/31/2000 20:30
18233,Anchorage,RED,VARIOUS,AK,12/31/2000 21:00
18234,Capitola,NaN,TRIANGLE,CA,12/31/2000 22:00
18235,Fountain Hills,NaN,NaN,AZ,12/31/2000 23:00
18236,Grant Park,NaN,TRIANGLE,IL,12/31/2000 23:00
18237,Spirit Lake,NaN,DISK,IA,12/31/2000 23:00
18238,Eagle River,NaN,NaN,WI,12/31/2000 23:45
18239,Eagle River,RED,LIGHT,WI,12/31/2000 23:45
18240,Ybor,NaN,OVAL,FL,12/31/2000 23:59

In [3]:
ufo.fillna(method='ffill')

,City,Colors Reported,Shape Reported,State,Time
0,Ithaca,NaN,TRIANGLE,NY,6/1/1930 22:00
1,Willingboro,NaN,OTHER,NJ,6/30/1930 20:00
2,Holyoke,NaN,OVAL,CO,2/15/1931 14:00
3,Abilene,NaN,DISK,KS,6/1/1931 13:00
4,New York Worlds Fair,NaN,LIGHT,NY,4/18/1933 19:00
5,Valley City,NaN,DISK,ND,9/15/1934 15:30
6,Crater Lake,NaN,CIRCLE,CA,6/15/1935 0:00
7,Alma,NaN,DISK,MI,7/15/1936 0:00
8,Eklutna,NaN,CIGAR,AK,10/15/1936 17:00
9,Hubbard,NaN,CYLINDER,OR,6/15/1937 0:00
10,Fontana,NaN,LIGHT,CA,8/15/1937 21:00
11,Waterloo,NaN,FIREBALL,AL,6/1/1939 20:00
12,Belton,RED,SPHERE,SC,6/30/1939 20:00
13,Keokuk,RED,OVAL,IA,7/7/1939 2:00
14,Ludington,RED,DISK,MI,6/1/1941 13:00
15,Forest Home,RED,CIRCLE,CA,7/2/1941 11:30
16,Los Angeles,RED,CIRCLE,CA,2/25/1942 0:00
17,Hapeville,RED,CIRCLE,GA,6/1/1942 22:30
18,Oneida,RED,RECTANGLE,TN,7/15/1942 1:00
19,Bering Sea,RED,OTHER,AK,4/30/1943 23:00
20,Nebraska,RED,DISK,NE,6/1/1943 15:00
21,Nebraska,RED,DISK,LA,8/15/1943 0:00
22,Nebraska,RED,LIGHT,LA,8/15/1943 0:00
23,Owensboro,RED,RECTANGLE,KY,10/15/1943 11:00
24,Wilderness,RED,DISK,WV,1/1/1944 10:00
25,San Diego,RED,CIGAR,CA,1/1/1944 12:00
26,Wilderness,RED,DISK,WV,1/1/1944 12:00
27,Clovis,RED,DISK,NM,4/2/1944 11:00
28,Los Alamos,RED,DISK,NM,6/1/1944 12:00
29,Ft. Duschene,RED,DISK,UT,6/30/1944 10:00
...,...,...,...,...,...
18211,Holyoke,BLUE,DIAMOND,MA,12/28/2000 18:00
18212,Carson,BLUE,DISK,CA,12/28/2000 18:20
18213,Pasadena,GREEN,FIREBALL,CA,12/28/2000 19:10
18214,Austin,GREEN,FORMATION,TX,12/29/2000 0:00
18215,El Campo,GREEN,OTHER,TX,12/29/2000 9:00
18216,Garden Grove,ORANGE,LIGHT,CA,12/29/2000 16:10
18217,Berthoud Pass,ORANGE,TRIANGLE,CO,12/29/2000 19:30
18218,Sisterdale,ORANGE,DIAMOND,TX,12/29/2000 20:00
18219,Garden Grove,ORANGE,CHEVRON,CA,12/29/2000 20:30
18220,Shasta Lake,BLUE,DISK,CA,12/29/2000 20:30
18221,Franklin,BLUE,DISK,NH,12/29/2000 20:50
18222,Albrightsville,BLUE,OTHER,PA,12/29/2000 21:00
18223,Greenville,BLUE,OTHER,SC,12/29/2000 22:00
18224,Eufaula,BLUE,DISK,OK,12/29/2000 23:30
18225,Simi Valley,BLUE,FORMATION,CA,12/30/2000 10:00
18226,San Francisco,BLUE,FORMATION,CA,12/30/2000 22:00
18227,San Francisco,BLUE,TRIANGLE,CA,12/30/2000 22:00
18228,Kingsville,BLUE,LIGHT,TX,12/31/2000 4:00
18229,Chicago,BLUE,DISK,IL,12/31/2000 11:45
18230,Pismo Beach,BLUE,OVAL,CA,12/31/2000 20:00
18231,Pismo Beach,BLUE,OVAL,CA,12/31/2000 20:00
18232,Lodi,BLUE,OVAL,WI,12/31/2000 20:30
18233,Anchorage,RED,VARIOUS,AK,12/31/2000 21:00
18234,Capitola,RED,TRIANGLE,CA,12/31/2000 22:00
18235,Fountain Hills,RED,TRIANGLE,AZ,12/31/2000 23:00
18236,Grant Park,RED,TRIANGLE,IL,12/31/2000 23:00
18237,Spirit Lake,RED,DISK,IA,12/31/2000 23:00
18238,Eagle River,RED,DISK,WI,12/31/2000 23:45
18239,Eagle River,RED,LIGHT,WI,12/31/2000 23:45
18240,Ybor,RED,OVAL,FL,12/31/2000 23:59

# Fill NA/NaN values using the specified method.

# method : {'backfill', 'bfill', 'pad', 'ffill', None}, default None
    Method to use for filling holes in reindexed Series
    pad / ffill: propagate last valid observation forward to next valid
    backfill / bfill: use NEXT valid observation to fill gap

In [5]:
ufo.fillna(method='bfill')

,City,Colors Reported,Shape Reported,State,Time
0,Ithaca,RED,TRIANGLE,NY,6/1/1930 22:00
1,Willingboro,RED,OTHER,NJ,6/30/1930 20:00
2,Holyoke,RED,OVAL,CO,2/15/1931 14:00
3,Abilene,RED,DISK,KS,6/1/1931 13:00
4,New York Worlds Fair,RED,LIGHT,NY,4/18/1933 19:00
5,Valley City,RED,DISK,ND,9/15/1934 15:30
6,Crater Lake,RED,CIRCLE,CA,6/15/1935 0:00
7,Alma,RED,DISK,MI,7/15/1936 0:00
8,Eklutna,RED,CIGAR,AK,10/15/1936 17:00
9,Hubbard,RED,CYLINDER,OR,6/15/1937 0:00
10,Fontana,RED,LIGHT,CA,8/15/1937 21:00
11,Waterloo,RED,FIREBALL,AL,6/1/1939 20:00
12,Belton,RED,SPHERE,SC,6/30/1939 20:00
13,Keokuk,RED,OVAL,IA,7/7/1939 2:00
14,Ludington,RED,DISK,MI,6/1/1941 13:00
15,Forest Home,RED,CIRCLE,CA,7/2/1941 11:30
16,Los Angeles,RED,RECTANGLE,CA,2/25/1942 0:00
17,Hapeville,RED,RECTANGLE,GA,6/1/1942 22:30
18,Oneida,RED,RECTANGLE,TN,7/15/1942 1:00
19,Bering Sea,RED,OTHER,AK,4/30/1943 23:00
20,Nebraska,RED,DISK,NE,6/1/1943 15:00
21,Owensboro,RED,LIGHT,LA,8/15/1943 0:00
22,Owensboro,RED,LIGHT,LA,8/15/1943 0:00
23,Owensboro,RED,RECTANGLE,KY,10/15/1943 11:00
24,Wilderness,RED,DISK,WV,1/1/1944 10:00
25,San Diego,RED,CIGAR,CA,1/1/1944 12:00
26,Wilderness,RED,DISK,WV,1/1/1944 12:00
27,Clovis,RED,DISK,NM,4/2/1944 11:00
28,Los Alamos,RED,DISK,NM,6/1/1944 12:00
29,Ft. Duschene,RED,DISK,UT,6/30/1944 10:00
...,...,...,...,...,...
18211,Holyoke,GREEN,DIAMOND,MA,12/28/2000 18:00
18212,Carson,GREEN,DISK,CA,12/28/2000 18:20
18213,Pasadena,GREEN,FIREBALL,CA,12/28/2000 19:10
18214,Austin,ORANGE,FORMATION,TX,12/29/2000 0:00
18215,El Campo,ORANGE,OTHER,TX,12/29/2000 9:00
18216,Garden Grove,ORANGE,LIGHT,CA,12/29/2000 16:10
18217,Berthoud Pass,BLUE,TRIANGLE,CO,12/29/2000 19:30
18218,Sisterdale,BLUE,DIAMOND,TX,12/29/2000 20:00
18219,Garden Grove,BLUE,CHEVRON,CA,12/29/2000 20:30
18220,Shasta Lake,BLUE,DISK,CA,12/29/2000 20:30
18221,Franklin,RED,DISK,NH,12/29/2000 20:50
18222,Albrightsville,RED,OTHER,PA,12/29/2000 21:00
18223,Greenville,RED,DISK,SC,12/29/2000 22:00
18224,Eufaula,RED,DISK,OK,12/29/2000 23:30
18225,Simi Valley,RED,FORMATION,CA,12/30/2000 10:00
18226,San Francisco,RED,FORMATION,CA,12/30/2000 22:00
18227,San Francisco,RED,TRIANGLE,CA,12/30/2000 22:00
18228,Kingsville,RED,LIGHT,TX,12/31/2000 4:00
18229,Chicago,RED,DISK,IL,12/31/2000 11:45
18230,Pismo Beach,RED,OVAL,CA,12/31/2000 20:00
18231,Pismo Beach,RED,OVAL,CA,12/31/2000 20:00
18232,Lodi,RED,VARIOUS,WI,12/31/2000 20:30
18233,Anchorage,RED,VARIOUS,AK,12/31/2000 21:00
18234,Capitola,RED,TRIANGLE,CA,12/31/2000 22:00
18235,Fountain Hills,RED,TRIANGLE,AZ,12/31/2000 23:00
18236,Grant Park,RED,TRIANGLE,IL,12/31/2000 23:00
18237,Spirit Lake,RED,DISK,IA,12/31/2000 23:00
18238,Eagle River,RED,LIGHT,WI,12/31/2000 23:45
18239,Eagle River,RED,LIGHT,WI,12/31/2000 23:45
18240,Ybor,NaN,OVAL,FL,12/31/2000 23:59

In [6]:
ufo.dropna(how='any')

,City,Colors Reported,Shape Reported,State,Time
12,Belton,RED,SPHERE,SC,6/30/1939 20:00
19,Bering Sea,RED,OTHER,AK,4/30/1943 23:00
36,Portsmouth,RED,FORMATION,VA,7/10/1945 1:30
44,Blairsden,GREEN,SPHERE,CA,6/30/1946 19:00
82,San Jose,BLUE,CHEVRON,CA,7/15/1947 21:00
84,Modesto,BLUE,DISK,CA,8/8/1947 22:00
91,Scipio,RED,SPHERE,IN,5/10/1948 19:00
111,Tarrant City,ORANGE,CIRCLE,AL,8/15/1949 22:00
129,Napa,GREEN,DISK,CA,6/10/1950 0:00
138,Coeur d'Alene,ORANGE,CIGAR,ID,7/2/1950 13:00
152,Irving,BLUE,DISK,KS,4/15/1951 0:30
157,Greenville,GREEN,DISK,MS,6/15/1951 20:30
163,Green River,GREEN,SPHERE,WY,7/3/1951 12:00
164,Provo,BLUE,DISK,UT,7/10/1951 23:30
174,Greenville,ORANGE,TRIANGLE,TX,4/15/1952 16:00
178,Norfolk,RED,FIREBALL,VA,6/1/1952 22:00
202,Arlington,GREEN,OVAL,VA,7/13/1952 21:00
226,Cambridge,RED,SPHERE,MA,4/1/1953 18:00
229,Midwest City,YELLOW,FIREBALL,OK,4/15/1953 16:00
238,Cleveland,RED,FIREBALL,OH,6/30/1953 0:00
249,Artesia,ORANGE,OTHER,NM,8/15/1953 19:00
256,Pendleton,GREEN,DISK,IN,11/21/1953 22:30
288,St. Louis Airport,RED,OVAL,MO,7/1/1954 21:00
289,Los Angeles,RED,CIRCLE,CA,7/1/1954 22:00
304,Beaumont,RED,DISK,TX,9/9/1954 12:30
311,Red Bank,ORANGE,CIRCLE,NJ,12/15/1954 23:10
314,Holbrook,YELLOW,EGG,MA,5/1/1955 15:00
323,Terre Haute,ORANGE,CIRCLE,IN,6/15/1955 0:00
354,Memphis,ORANGE,CYLINDER,TN,6/1/1956 20:00
363,Vista,ORANGE,CIGAR,CA,6/15/1956 19:15
...,...,...,...,...,...
18110,Gilbert,RED,LIGHT,AZ,12/11/2000 23:45
18115,Madison,RED GREEN,TEARDROP,OH,12/12/2000 18:45
18117,Concord,RED GREEN,CIRCLE,NH,12/12/2000 23:10
18121,Redwood Valley,BLUE,LIGHT,CA,12/15/2000 1:09
18123,Waldorf,GREEN,LIGHT,MD,12/15/2000 5:30
18127,North Pole,ORANGE,SPHERE,AK,12/15/2000 16:36
18129,Beaver,RED,DISK,PA,12/15/2000 18:25
18134,Graham,GREEN,LIGHT,WA,12/16/2000 0:20
18141,Sebastopol,YELLOW,CIRCLE,CA,12/17/2000 18:00
18144,Medina,ORANGE,TRIANGLE,OH,12/17/2000 19:30
18148,Highland Park,BLUE,VARIOUS,NJ,12/18/2000 2:30
18158,Woodland,ORANGE,LIGHT,CA,12/19/2000 23:30
18167,Gilbert,RED,CIRCLE,AZ,12/21/2000 19:05
18170,MM 110,BLUE,CIRCLE,AZ,12/22/2000 3:00
18172,Toomsuba,RED,OVAL,MS,12/23/2000 4:00
18177,Chandler,RED,LIGHT,AZ,12/23/2000 22:00
18181,Fortuna,ORANGE,CIRCLE,CA,12/24/2000 18:00
18184,Plymouth,GREEN,FIREBALL,OH,12/24/2000 22:00
18191,Fallston,RED,VARIOUS,MD,12/25/2000 19:15
18192,Atlanta,ORANGE,LIGHT,GA,12/25/2000 20:30
18194,Walpole,GREEN,FIREBALL,NH,12/26/2000 18:20
18195,Walpole,GREEN,FIREBALL,NH,12/26/2000 18:20
18196,Brocton,GREEN,OVAL,MA,12/26/2000 18:23
18197,Greenfiled,GREEN,FIREBALL,MA,12/26/2000 18:30
18210,Monument Valley,BLUE,OTHER,UT,12/28/2000 17:51
18213,Pasadena,GREEN,FIREBALL,CA,12/28/2000 19:10
18216,Garden Grove,ORANGE,LIGHT,CA,12/29/2000 16:10
18220,Shasta Lake,BLUE,DISK,CA,12/29/2000 20:30
18233,Anchorage,RED,VARIOUS,AK,12/31/2000 21:00
18239,Eagle River,RED,LIGHT,WI,12/31/2000 23:45